// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mysqldb;
using Mysqldb.model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mysqldb.Migrations
{
    [DbContext(typeof(Wxusers))]
    [Migration("20230515041821_limit1")]
    partial class limit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Account", b =>
                {
                    b.Property<string>("Nums")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Birth")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dept")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Faildate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Issudate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Legal")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nation")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Paddress")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pname")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pnums")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Range")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Regcapital")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Validdate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Nums");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Aitoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("aitokens", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Asset", b =>
                {
                    b.Property<string>("Qrcode")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Img")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("Money")
                        .HasColumnType("double precision");

                    b.Property<string>("Pname")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Pointid")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Userid")
                        .HasColumnType("text");

                    b.Property<int>("kind")
                        .HasColumnType("integer");

                    b.HasKey("Qrcode");

                    b.HasIndex("Pointid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("Mysqldb.Bank", b =>
                {
                    b.Property<string>("bankID")
                        .HasColumnType("text");

                    b.Property<string>("bankName")
                        .HasColumnType("text");

                    b.Property<string>("parentID")
                        .HasColumnType("text");

                    b.HasKey("bankID");

                    b.HasIndex("parentID");

                    b.ToTable("banks");
                });

            modelBuilder.Entity("Mysqldb.Booking", b =>
                {
                    b.Property<string>("Unionid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FirstDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Forthdatae")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Information")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsProccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Nums")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("Seconddatae")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Straff")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("Thirddatae")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Wxopenid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Unionid");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Cloudprinter", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Bankcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Fprname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Gpsflag")
                        .HasColumnType("boolean");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PrLeft")
                        .HasColumnType("integer");

                    b.Property<int>("PrTop")
                        .HasColumnType("integer");

                    b.Property<string>("Regcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sprname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("straff")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Code");

                    b.ToTable("cloundprinters", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Contract", b =>
                {
                    b.Property<string>("number")
                        .HasColumnType("text");

                    b.Property<double>("money")
                        .HasColumnType("double precision");

                    b.Property<string>("name")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("num")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("product")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("number");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Credittoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("fileId")
                        .HasColumnType("integer");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Express", b =>
                {
                    b.Property<string>("expressID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("phoneLast")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("transID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("expressID");

                    b.HasIndex("transID")
                        .IsUnique();

                    b.ToTable("express", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Gps", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("gps");
                });

            modelBuilder.Entity("Mysqldb.LoanProcess", b =>
                {
                    b.Property<string>("ProcID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("bankid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("bankname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("date11")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date12")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date21")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date22")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date31")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date32")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date41")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date42")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date51")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date52")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("flag")
                        .HasColumnType("integer");

                    b.Property<int?>("loantype")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("parentid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff1")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff2")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff3")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff4")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff5")
                        .HasColumnType("text");

                    b.HasKey("ProcID");

                    b.ToTable("loanProcesses");
                });

            modelBuilder.Entity("Mysqldb.Loans", b =>
                {
                    b.Property<string>("LoanID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Bankname")
                        .HasColumnType("text");

                    b.Property<string>("Money")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Vdate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("LoanID");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Loanuser", b =>
                {
                    b.Property<string>("straff")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Ace")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsLogin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("bankid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("straff_name")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("unionid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("straff");

                    b.ToTable("loanusers");
                });

            modelBuilder.Entity("Mysqldb.Member", b =>
                {
                    b.Property<string>("userid")
                        .HasColumnType("text");

                    b.Property<string>("department")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.HasKey("userid");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Mysqldb.Order_TBL", b =>
                {
                    b.Property<string>("orderID")
                        .HasColumnType("text");

                    b.Property<int>("isCheck")
                        .HasColumnType("integer");

                    b.Property<string>("openid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("orderInfo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("orderName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("orderTel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("orderTime")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("straffDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("straffID")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("sub")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("orderID");

                    b.HasIndex("straffID");

                    b.ToTable("Order_TBLs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Printers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("printers");
                });

            modelBuilder.Entity("Mysqldb.Rcbstraff", b =>
                {
                    b.Property<string>("Straff")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ace")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unionid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Straff");

                    b.ToTable("rcbstraffs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Straff", b =>
                {
                    b.Property<string>("straffID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("aceID")
                        .HasColumnType("integer");

                    b.Property<string>("acess")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("bankID")
                        .HasColumnType("text");

                    b.Property<string>("openid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("straffAge")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("straffName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("straffSex")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("straffTel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("straffID");

                    b.HasIndex("bankID");

                    b.ToTable("Straffs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Subankdata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CR01")
                        .HasColumnType("double precision");

                    b.Property<double>("CR02")
                        .HasColumnType("double precision");

                    b.Property<double>("CR03")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp1")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp10")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp11")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp12")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp13")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp14")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp15")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp16")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp17")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp2")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp3")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp4")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp5")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp6")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp7")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp8")
                        .HasColumnType("double precision");

                    b.Property<double>("Comp9")
                        .HasColumnType("double precision");

                    b.Property<double>("Count01")
                        .HasColumnType("double precision");

                    b.Property<double>("Cunnt02")
                        .HasColumnType("double precision");

                    b.Property<double>("Dept")
                        .HasColumnType("double precision");

                    b.Property<double>("Ebank0")
                        .HasColumnType("double precision");

                    b.Property<double>("Ebank1")
                        .HasColumnType("double precision");

                    b.Property<double>("Ebank2")
                        .HasColumnType("double precision");

                    b.Property<double>("Ebank3")
                        .HasColumnType("double precision");

                    b.Property<double>("Gold")
                        .HasColumnType("double precision");

                    b.Property<double>("LowDept")
                        .HasColumnType("double precision");

                    b.Property<double>("NewDept")
                        .HasColumnType("double precision");

                    b.Property<double>("PubDept")
                        .HasColumnType("double precision");

                    b.Property<double>("Risk")
                        .HasColumnType("double precision");

                    b.Property<double>("Risk02")
                        .HasColumnType("double precision");

                    b.Property<double>("RiskK01")
                        .HasColumnType("double precision");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("TRAIN01")
                        .HasColumnType("double precision");

                    b.Property<double>("TRAIN02")
                        .HasColumnType("double precision");

                    b.Property<double>("TRAIN03")
                        .HasColumnType("double precision");

                    b.Property<double>("XD01")
                        .HasColumnType("double precision");

                    b.Property<double>("XD02")
                        .HasColumnType("double precision");

                    b.Property<string>("mdate")
                        .HasColumnType("text");

                    b.Property<double>("netadd")
                        .HasColumnType("double precision");

                    b.Property<double>("netred")
                        .HasColumnType("double precision");

                    b.Property<double>("nums")
                        .HasColumnType("double precision");

                    b.Property<string>("sub_id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subankdatas", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Supernotice", b =>
                {
                    b.Property<string>("NoticeId")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<List<Approval>>("Approvals")
                        .HasColumnType("jsonb");

                    b.Property<int>("Approverstep")
                        .HasColumnType("integer");

                    b.Property<Noticedata>("Noticedata")
                        .HasColumnType("jsonb");

                    b.Property<Orderdata>("Orderdata")
                        .HasColumnType("jsonb");

                    b.HasKey("NoticeId");

                    b.ToTable("Supernotices", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Supernoticeapproval", b =>
                {
                    b.Property<string>("Noticeid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<Approval_userid>>("Users")
                        .HasColumnType("jsonb");

                    b.HasKey("Noticeid");

                    b.ToTable("Supernoticeapprovals", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Trans_TBL", b =>
                {
                    b.Property<string>("busID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("openid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("prepay_ID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("productID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("sendInfo")
                        .HasColumnType("integer");

                    b.Property<string>("straffID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("transBack")
                        .HasColumnType("integer");

                    b.Property<DateTime>("transDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("transID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("transMoney")
                        .HasColumnType("numeric");

                    b.Property<string>("transType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("busID");

                    b.HasIndex("productID");

                    b.ToTable("Trans_TBLs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Appopenid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WxUnionid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Wxopenid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mysqldb.Workdepart", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint");

                    b.Property<int>("level")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("order")
                        .HasColumnType("bigint");

                    b.Property<long>("parentid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("wrokdeparts");
                });

            modelBuilder.Entity("Mysqldb.Wxsession", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("sessionkey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("unionid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("code");

                    b.ToTable("wxsessions");
                });

            modelBuilder.Entity("Mysqldb.asset_state", b =>
                {
                    b.Property<long>("spanid")
                        .HasMaxLength(50)
                        .HasColumnType("bigint");

                    b.Property<string>("operator_content")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("operator_id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("origin_id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("qrcode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("state")
                        .HasColumnType("integer");

                    b.Property<string>("target_id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("spanid");

                    b.ToTable("asset_states", (string)null);
                });

            modelBuilder.Entity("Mysqldb.bankcoord", b =>
                {
                    b.Property<string>("bankID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("LAT")
                        .HasColumnType("double precision");

                    b.Property<double>("LON")
                        .HasColumnType("double precision");

                    b.Property<string>("bankName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("bankID");

                    b.ToTable("bankcoords", (string)null);
                });

            modelBuilder.Entity("Mysqldb.customers", b =>
                {
                    b.Property<string>("openid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerAdr1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerAdr2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerAdr3")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerAdr4")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerAdr5")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerTel1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerTel2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerTel3")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerTel4")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("customerTel5")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("straffID")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("unionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("openid");

                    b.HasIndex("straffID");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Mysqldb.employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Depart")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DepartID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("acces")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("EmployeeID");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Mysqldb.gold_TBL", b =>
                {
                    b.Property<string>("goldID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("goldMoney")
                        .HasColumnType("numeric");

                    b.Property<string>("goldName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("goldPro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("goldSize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("goldType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("remark")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("goldID");

                    b.ToTable("gold_TBLs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.hangjob", b =>
                {
                    b.Property<string>("jobid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ace")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("date_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("date_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("date_warn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isdel")
                        .HasColumnType("boolean");

                    b.Property<bool>("iswarn")
                        .HasColumnType("boolean");

                    b.Property<string>("procid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("jobid");

                    b.ToTable("hangjobs", (string)null);
                });

            modelBuilder.Entity("Mysqldb.model.First", b =>
                {
                    b.Property<string>("Transid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<List<Transfile>>("Attachs")
                        .HasColumnType("jsonb");

                    b.Property<string>("Copypersion")
                        .HasColumnType("text");

                    b.Property<Cust>("Cust")
                        .HasColumnType("jsonb");

                    b.Property<List<Employeeinfo>>("Relay")
                        .HasColumnType("jsonb");

                    b.Property<Trans_status>("Trans_Status")
                        .HasColumnType("jsonb");

                    b.Property<long>("Transtime")
                        .HasColumnType("bigint");

                    b.HasKey("Transid");

                    b.ToTable("Firsts");
                });

            modelBuilder.Entity("Mysqldb.model.Limit", b =>
                {
                    b.Property<string>("Limitid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Approval")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Approval_content")
                        .HasColumnType("text");

                    b.Property<List<Transfile>>("Attachs")
                        .HasColumnType("jsonb");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conttype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("Departid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Departname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isover")
                        .HasColumnType("boolean");

                    b.Property<string>("Leaderid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Leadername")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Overday")
                        .HasColumnType("integer");

                    b.Property<string>("Relay_approval")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Relay_approval_content")
                        .HasColumnType("text");

                    b.Property<long>("Relay_approval_time")
                        .HasColumnType("bigint");

                    b.Property<string>("Relay_content")
                        .HasColumnType("text");

                    b.Property<string>("Relay_departid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Relay_departname")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Relay_leaderid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Relay_time")
                        .HasColumnType("bigint");

                    b.Property<string>("Relay_userid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Transtime")
                        .HasColumnType("bigint");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Limitid");

                    b.ToTable("limits", (string)null);
                });

            modelBuilder.Entity("Mysqldb.myRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Mysqldb.wxunionid", b =>
                {
                    b.Property<string>("WxUnionid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Appopenid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gappid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Subscribe")
                        .HasColumnType("boolean");

                    b.Property<string>("Wxopenid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Xappid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("WxUnionid");

                    b.ToTable("unionids", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Mysqldb.myRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Mysqldb.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Mysqldb.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Mysqldb.myRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mysqldb.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Mysqldb.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mysqldb.Asset", b =>
                {
                    b.HasOne("Mysqldb.Gps", "Point")
                        .WithMany()
                        .HasForeignKey("Pointid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Point");
                });

            modelBuilder.Entity("Mysqldb.Bank", b =>
                {
                    b.HasOne("Mysqldb.Bank", "parent")
                        .WithMany("Children")
                        .HasForeignKey("parentID");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("Mysqldb.Express", b =>
                {
                    b.HasOne("Mysqldb.Trans_TBL", "trans")
                        .WithOne("express")
                        .HasForeignKey("Mysqldb.Express", "transID");

                    b.Navigation("trans");
                });

            modelBuilder.Entity("Mysqldb.Order_TBL", b =>
                {
                    b.HasOne("Mysqldb.Straff", "straff")
                        .WithMany("order")
                        .HasForeignKey("straffID");

                    b.Navigation("straff");
                });

            modelBuilder.Entity("Mysqldb.Straff", b =>
                {
                    b.HasOne("Mysqldb.Bank", "bank")
                        .WithMany()
                        .HasForeignKey("bankID");

                    b.Navigation("bank");
                });

            modelBuilder.Entity("Mysqldb.Trans_TBL", b =>
                {
                    b.HasOne("Mysqldb.gold_TBL", "goods")
                        .WithMany()
                        .HasForeignKey("productID");

                    b.Navigation("goods");
                });

            modelBuilder.Entity("Mysqldb.bankcoord", b =>
                {
                    b.HasOne("Mysqldb.Bank", "bank")
                        .WithOne("bankcoord")
                        .HasForeignKey("Mysqldb.bankcoord", "bankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bank");
                });

            modelBuilder.Entity("Mysqldb.customers", b =>
                {
                    b.HasOne("Mysqldb.Straff", "straff")
                        .WithMany()
                        .HasForeignKey("straffID");

                    b.Navigation("straff");
                });

            modelBuilder.Entity("Mysqldb.Bank", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("bankcoord");
                });

            modelBuilder.Entity("Mysqldb.Straff", b =>
                {
                    b.Navigation("order");
                });

            modelBuilder.Entity("Mysqldb.Trans_TBL", b =>
                {
                    b.Navigation("express");
                });
#pragma warning restore 612, 618
        }
    }
}
