name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
on:
  push:
    
    # Publish semver tags as releases.
 
    tags-ignore:
      - main
      
env:
 IMAGE_NAME: ${{ github.ref_name }}
 REGISTRY: registry.gitlab.com
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
      with:
        submodules: 'true'

    - name: push-dockerimage
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to dockergitlab-${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GITLABUSER }}
        password: ${{ secrets.GITLABPASSWORD }} 
    - name: Build and push
     
      uses: docker/build-push-action@v3
     # if: startsWith(github.ref, 'refs/tags/')
      with:
          context: ./workauto
          #file: ./corp/workauto/workauto/Dockerfile
          push: true
          
          platforms: linux/amd64
         
          tags: rcbblc/corp:${{ env.IMAGE_NAME }},rcbblc/corp:latest
         
          cache-from: type=registry,ref=rcbblc/corp:${{ env.IMAGE_NAME }}
          cache-to: type=inline
